######################################################################
# Automatically generated by qmake (3.1) Thu Feb 9 09:43:30 2023
######################################################################

TEMPLATE = app
TARGET = box
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += window.h
SOURCES += main.cpp
